var routeDetails = {
  "C1 CCSU Connector": {
    "One Way Travel Time": "13 minutes",
    "One Way Mileage": "3.1 miles",
    "Service Span": "Seven days a week, 18 hours a day on Monday to Saturday (6am to Midnight) and 12 hours (8 am to 8pm) on Sundays.",
    "Service Pattern": "The CCSU shuttle will operate in both directions, laying over at Cedar or East depending upon the direction of travel. Bus stops will be established along the route at convenient locations near important buildings on campus.",
    "Weekday AM Peak": "15",
    "Weekday Midday": "20",
    "Weekday PM Peak": "15",
    "Weekday Evening": "30",
    "Saturday AM Peak": "",
    "Saturday Midday": "20",
    "Saturday PM Peak": "",
    "Saturday Evening": "30",
    "Sunday AM Peak": "",
    "Sunday Midday": "30",
    "Sunday PM Peak": "",
    "Sunday Evening": ""
  },
  "C2 Hospitals - Capitol Connector": {
    "One Way Travel Time": "14 minutes",
    "One Way Mileage": "3.4 miles",
    "Service Span": "Seven days a week, 18 hours a day on Monday to Saturday (6am to Midnight) and 12 hours (8 am to 8pm) on Sundays.",
    "Service Pattern": "The CCSU shuttle will operate in both directions, laying over at Cedar or East depending upon the direction of travel. Bus stops will be established along the route at convenient locations near important buildings on campus.",
    "Weekday AM Peak": "15",
    "Weekday Midday": "20",
    "Weekday PM Peak": "15",
    "Weekday Evening": "30",
    "Saturday AM Peak": "",
    "Saturday Midday": "20",
    "Saturday PM Peak": "",
    "Saturday Evening": "30",
    "Sunday AM Peak": "",
    "Sunday Midday": "30",
    "Sunday PM Peak": "",
    "Sunday Evening": ""
  },
  "C3 Newington Circulator": {
    "One Way Mileage": "10.7 miles",
    "One Way Travel Time": "30 minutes",
    "Service Span": "Seven days a week, 18 hours a day on Monday to Saturday (6am to Midnight) and 12 hours (8 am to 8pm) on Sundays.",
    "Service Pattern": "The route will operate in local service stopping at all bus stops along its route.",
    "Weekday AM Peak": "30",
    "Weekday Midday": "60",
    "Weekday PM Peak": "30",
    "Weekday Evening": "60",
    "Saturday AM Peak": "",
    "Saturday Midday": "60",
    "Saturday PM Peak": "",
    "Saturday Evening": "60",
    "Sunday AM Peak": "",
    "Sunday Midday": "60",
    "Sunday PM Peak": "",
    "Sunday Evening": ""
  },
  "C4 West Hartford - Bishops Corner Connector": {
    "Service Pattern": "This route would operate in local service stopping at all bus stops along its routing.",
    "One Way Travel Time": "21 minutes",
    "One Way Mileage": "5.4 mile",
    "Service Span": "Seven days a week, 18 hours a day on Monday to Saturday (6am to Midnight) and 12 hours (8 am to 8pm) on Sundays.",
    "Weekday AM Peak": "60",
    "Weekday Midday": "60",
    "Weekday PM Peak": "60",
    "Weekday Evening": "60",
    "Saturday AM Peak": "",
    "Saturday Midday": "60",
    "Saturday PM Peak": "",
    "Saturday Evening": "60",
    "Sunday AM Peak": "",
    "Sunday Midday": "60",
    "Sunday PM Peak": "",
    "Sunday Evening": ""
  },

  "BX1 Waterbury Express": {
    "One Way Travel Time": "70 minutes",
    "One Way Mileage": "34.4 miles",
    "Service Pattern": "All trips operate from the Waterbury train station via the transit center, Exit 23 park and ride, Plantsville park and ride, New Britain station, Sigourney Street station and then via the downtown Hartford express bus loop (Farmington, Asylum, Main, Capitol) making all local stops when on-street. The loop would be operated clockwise in the morning and counterclockwise in the afternoon.",
    "Service Span": "This route will operate only on weekdays during AM and PM peak periods, from 6am to 9am and from 3pm to 6pm.",
    "Weekday AM Peak": "30",
    "Weekday Midday": "",
    "Weekday PM Peak": "30",
    "Weekday Evening": "",
    "Saturday AM Peak": "",
    "Saturday Midday": "",
    "Saturday PM Peak": "",
    "Saturday Evening": "",
    "Sunday AM Peak": "",
    "Sunday Midday": "",
    "Sunday PM Peak": "",
    "Sunday Evening": ""

  },
  "BX2 Cheshire Express": {
    "One Way Mileage": "28.5 miles",
    "One Way Travel Time": "56 minutes",
    "Service Span": "This route will operate only on weekdays during AM and PM peak periods, from 6am to 9am and from 3pm to 6pm.",
    "Service Pattern": "All trips operate from the Exit 26 park-and-ride, Plantsville park-and-ride, New Britain station, Sigourney Street station and then via the downtown Hartford express bus loop (Farmington, Asylum, Main, Capitol) making all local stops when on-street. The loop would be operated clockwise in the morning and counterclockwise in the afternoon.",
    "Weekday AM Peak": "30",
    "Weekday Midday": "",
    "Weekday PM Peak": "30",
    "Weekday Evening": "",
    "Saturday AM Peak": "",
    "Saturday Midday": "",
    "Saturday PM Peak": "",
    "Saturday Evening": "",
    "Sunday AM Peak": "",
    "Sunday Midday": "",
    "Sunday PM Peak": "",
    "Sunday Evening": ""
  },
  "BX3 Waterbury Cheshire Off-Peak Express": {
    "One Way Mileage": "34.4 miles",
    "One Way Travel Time": "70 minutes",
    "Service Pattern": "All trips operate between Waterbury, Exit 23 park-and-ride, Exit 26 park-and-ride, Plantsville park-and-ride, New Britain station, Sigourney Street station and then via the downtown Hartford express bus loop (Farmington, Asylum, Main, Capitol) making all local stops when on-street. The loop would be operated clockwise in the morning and counterclockwise in the afternoon and evening.",
    "Service Span": "This route will operate only during off-peak periods Monday through Sunday.",
    "Weekday AM Peak": "",
    "Weekday Midday": "60",
    "Weekday PM Peak": "",
    "Weekday Evening": "120",
    "Saturday AM Peak": "",
    "Saturday Midday": "60",
    "Saturday PM Peak": "",
    "Saturday Evening": "120",
    "Sunday AM Peak": "",
    "Sunday Midday": "120",
    "Sunday PM Peak": "",
    "Sunday Evening": ""
  },

  "West Hartford Place via Park": {
    "Service Pattern": "All trips operate in local transit service from West Hartford Place mall to downtown Hartford making all local stops.",
    "One Way Travel Time": "25 minutes",
    "One Way Mileage": "3.8 miles",
    "Service Span": "Seven days a week, 18 hours a day on Monday to Saturday (6am to Midnight) and 12 hours (8 am to 8pm) on Sundays.",
    "Weekday AM Peak": "20",
    "Weekday Midday": "40",
    "Weekday PM Peak": "20",
    "Weekday Evening": "60",
    "Saturday AM Peak": "",
    "Saturday Midday": "30",
    "Saturday PM Peak": "",
    "Saturday Evening": "60",
    "Sunday AM Peak": "",
    "Sunday Midday": "60",
    "Sunday PM Peak": "",
    "Sunday Evening": ""
  },


  "West Hartford Place via Park and Kane St": {
    "Service Pattern": "All trips operate in local transit service between West Hartford Place mall and downtown Hartford making all local stops.",
    "One Way Travel Time": "29 minutes",
    "One Way Mileage": "4.1 miles",
    "Service Span": "This service operates only during midday periods only (9am - 3pm) Monday through Friday.",
    "Weekday AM Peak": "",
    "Weekday Midday": "40",
    "Weekday PM Peak": "",
    "Weekday Evening": "",
    "Saturday AM Peak": "",
    "Saturday Midday": "",
    "Saturday PM Peak": "",
    "Saturday Evening": "",
    "Sunday AM Peak": "",
    "Sunday Midday": "",
    "Sunday PM Peak": "",
    "Sunday Evening": ""
  },


  "Westfarms via Park": {
    "Service Pattern": "All trips operate in local transit service between Westfarms Mall and downtown Hartford making all local stops.",
    "One Way Travel Time": "50 minutes",
    "One Way Mileage": "7.1 miles",
    "Service Span": "This route operates Monday through Saturday from 6am to 6pm.",
    "Weekday AM Peak": "40",
    "Weekday Midday": "40",
    "Weekday PM Peak": "40",
    "Weekday Evening": "",
    "Saturday AM Peak": "",
    "Saturday Midday": "30",
    "Saturday PM Peak": "",
    "Saturday Evening": "",
    "Sunday AM Peak": "",
    "Sunday Midday": "",
    "Sunday PM Peak": "",
    "Sunday Evening": ""
  },

  "Hartford Newington Local": {
    "Service Pattern": "All trips operate in local transit service between Newington and Hartford making all local stops.",
    "One Way Travel Time": "30 minutes",
    "One Way Mileage": "6.5 miles",
    "Service Span": "Seven days a week, 18 hours a day on Monday to Saturday (6am to Midnight) and 12 hours (8am to 8pm) on Sundays.",
    "Weekday AM Peak": "20",
    "Weekday Midday": "30",
    "Weekday PM Peak": "20",
    "Weekday Evening": "60",
    "Saturday AM Peak": "",
    "Saturday Midday": "30",
    "Saturday PM Peak": "",
    "Saturday Evening": "60",
    "Sunday AM Peak": "",
    "Sunday Midday": "60",
    "Sunday PM Peak": "",
    "Sunday Evening": ""
  },


  "Charter Oak Marketplace West Hartford Place via NB Ave": {
    "Service Pattern": "All trips operate in local transit service between West Hartford Place mall and downtown Hartford making all local stops.",
    "One Way Travel Time": "39 minutes",
    "One Way Mileage": "5.2 miles",
    "Service Span": "Seven days a week, 18 hours a day on Monday to Saturday (6am to Midnight) and 12 hours (8am to 8pm) on Sundays.",
    "Weekday AM Peak": "30",
    "Weekday Midday": "60",
    "Weekday PM Peak": "30",
    "Weekday Evening": "60",
    "Saturday AM Peak": "",
    "Saturday Midday": "60",
    "Saturday PM Peak": "",
    "Saturday Evening": "60",
    "Sunday AM Peak": "",
    "Sunday Midday": "60",
    "Sunday PM Peak": "",
    "Sunday Evening": ""
  },

  "Elmwood via New Britain Ave": {
    "Service Pattern": "All trips operate in local transit service between Elmwood and downtown Hartford making all local stops.",
    "One Way Travel Time": "34 minutes",
    "One Way Mileage": "4.9 miles",
    "Service Span": "Seven days a week, 18 hours a day on Monday to Saturday (6am to Midnight) and 12 hours (8am to 8pm) on Sundays.",
    "Weekday AM Peak": "20",
    "Weekday Midday": "60",
    "Weekday PM Peak": "20",
    "Weekday Evening": "60",
    "Saturday AM Peak": "",
    "Saturday Midday": "60",
    "Saturday PM Peak": "",
    "Saturday Evening": "60",
    "Sunday AM Peak": "",
    "Sunday Midday": "60",
    "Sunday PM Peak": "",
    "Sunday Evening": ""
  },


  "Capitol - Berlin Turnpike via Willard": {
    "Service Pattern": "All trips operate in local transit service between Berlin Turnpike and downtown Hartford making all local stops.",
    "One Way Travel Time": "41 minutes",
    "One Way Mileage": "11.9 miles",
    "Service Span": "Monday through Saturday from 6am to 6pm. No service during evenings and on Sundays.",
    "Weekday AM Peak": "30",
    "Weekday Midday": "30",
    "Weekday PM Peak": "30",
    "Weekday Evening": "",
    "Saturday AM Peak": "",
    "Saturday Midday": "30",
    "Saturday PM Peak": "",
    "Saturday Evening": "",
    "Sunday AM Peak": "",
    "Sunday Midday": "",
    "Sunday PM Peak": "",
    "Sunday Evening": ""
  },

  "Arch Street": {
    "Service Pattern": "All trips operate in local transit service between Meriden and New Britain station making all local stops.",
    "One Way Travel Time": "30 minutes",
    "One Way Mileage": "10.1 miles",
    "Service Span": "Seven days a week, 18 hours a day on Monday to Saturday (6am to Midnight) and 12 hours (8 am to 8pm) on Sundays.",
    "Weekday AM Peak": "60",
    "Weekday Midday": "60",
    "Weekday PM Peak": "60",
    "Weekday Evening": "60",
    "Saturday AM Peak": "",
    "Saturday Midday": "60",
    "Saturday PM Peak": "",
    "Saturday Evening": "60",
    "Sunday AM Peak": "",
    "Sunday Midday": "60",
    "Sunday PM Peak": "",
    "Sunday Evening": ""
  },

  "Burritt Street": {
    "Service Pattern": "All trips operate in local transit service between Slater Road and New Britain station making all local stops.",
    "One Way Travel Time": "20 minutes",
    "One Way Mileage": "5.6 miles",
    "Service Span": "Seven days a week, 18 hours a day on Monday to Saturday (6am to Midnight) and 12 hours (8 am to 8pm) on Sundays.",
    "Weekday AM Peak": "30",
    "Weekday Midday": "60",
    "Weekday PM Peak": "30",
    "Weekday Evening": "60",
    "Saturday AM Peak": "",
    "Saturday Midday": "60",
    "Saturday PM Peak": "",
    "Saturday Evening": "60",
    "Sunday AM Peak": "",
    "Sunday Midday": "60",
    "Sunday PM Peak": "",
    "Sunday Evening": ""
  },

  "Corbin Avenue": {
    "Service Pattern": "All trips operate in local transit service between Tunxis Community College and New Britain station making all local stops.",
    "One Way Travel Time": "30 minutes",
    "One Way Mileage": "9.4 miles",
    "Service Span": "Seven days a week, 18 hours a day on Monday to Saturday (6am to Midnight) and 12 hours (8 am to 8pm) on Sundays.",
    "Weekday AM Peak": "30",
    "Weekday Midday": "60",
    "Weekday PM Peak": "30",
    "Weekday Evening": "60",
    "Saturday AM Peak": "",
    "Saturday Midday": "60",
    "Saturday PM Peak": "",
    "Saturday Evening": "60",
    "Sunday AM Peak": "",
    "Sunday Midday": "60",
    "Sunday PM Peak": "",
    "Sunday Evening": ""
  },

  "Farmington Avenue": {
    "Service Pattern": "All trips operate in local transit service between the UConn Health Center and New Britain station making all local stops.",
    "One Way Travel Time": "30 minutes",
    "One Way Mileage": "7.0 miles",
    "Service Span": "Seven days a week, 18 hours a day on Monday to Saturday (6am to Midnight) and 12 hours (8 am to 8pm) on Sundays.",
    "Weekday AM Peak": "60",
    "Weekday Midday": "60",
    "Weekday PM Peak": "60",
    "Weekday Evening": "60",
    "Saturday AM Peak": "",
    "Saturday Midday": "60",
    "Saturday PM Peak": "",
    "Saturday Evening": "60",
    "Sunday AM Peak": "",
    "Sunday Midday": "60",
    "Sunday PM Peak": "",
    "Sunday Evening": ""
  },

  "Oak Street": {
    "Service Pattern": "All trips operate in local transit service between Cedar Street station and New Britain station making all local stops.",
    "One Way Travel Time": "15 minutes",
    "One Way Mileage": "3.8 miles",
    "Service Span": "Seven days a week, 18 hours a day on Monday to Saturday (6am to Midnight) and 12 hours (8 am to 8pm) on Sundays.",
    "Weekday AM Peak": "30",
    "Weekday Midday": "60",
    "Weekday PM Peak": "30",
    "Weekday Evening": "60",
    "Saturday AM Peak": "",
    "Saturday Midday": "60",
    "Saturday PM Peak": "",
    "Saturday Evening": "60",
    "Sunday AM Peak": "",
    "Sunday Midday": "60",
    "Sunday PM Peak": "",
    "Sunday Evening": ""
  },

  "Plainville/Bristol": {
    "Service Pattern": "All trips operate in local transit service between Forestville and New Britain station making all local stops.",
    "One Way Travel Time": "30 minutes",
    "One Way Mileage": "6.6 miles",
    "Service Span": "Seven days a week, 18 hours a day on Monday to Saturday (6am to Midnight) and 12 hours (8 am to 8pm) on Sundays.",
    "Weekday Midday": "60",
    "Weekday PM Peak": "60",
    "Weekday Evening": "60",
    "Saturday AM Peak": "",
    "Saturday Midday": "60",
    "Saturday PM Peak": "",
    "Saturday Evening": "60",
    "Sunday AM Peak": "",
    "Sunday Midday": "60",
    "Sunday PM Peak": "",
    "Sunday Evening": ""
  },

  "Berlin Turnpike": {
    "Service Pattern": "All trips operate in local transit service between the Berlin Turnpike and New Britain station making all local stops.",
    "One Way Travel Time": "30 minutes",
    "One Way Mileage": "7.4 miles",
    "Service Span": "Weekday peak periods only, from 6am to 9am and from 3pm to 6pm. ",
    "Weekday AM Peak": "60",
    "Weekday Midday": "",
    "Weekday PM Peak": "60",
    "Weekday Evening": "",
    "Saturday AM Peak": "",
    "Saturday Midday": "",
    "Saturday PM Peak": "",
    "Saturday Evening": "",
    "Sunday AM Peak": "",
    "Sunday Midday": "",
    "Sunday PM Peak": "",
    "Sunday Evening": ""
  },

  "Berlin Turnpike (Cromwell)": {
    "Service Pattern": "All trips operate in local transit service between the Cromwell Wal-Mart and New Britain station making all local stops.",
    "One Way Travel Time": "45 minutes",
    "One Way Mileage": "10.5 miles",
    "Service Span": "Seven days a week, 18 hours a day on Monday to Saturday (6am to Midnight) and 12 hours (8 am to 8pm) on Sundays.",
    "Weekday AM Peak": "90",
    "Weekday Midday": "90",
    "Weekday PM Peak": "90",
    "Weekday Evening": "90",
    "Saturday AM Peak": "",
    "Saturday Midday": "90",
    "Saturday PM Peak": "",
    "Saturday Evening": "90",
    "Sunday AM Peak": "",
    "Sunday Midday": "90",
    "Sunday PM Peak": "",
    "Sunday Evening": ""
  },

  "Combined South and East Street": {
    "Service Pattern": "All trips operate in local transit service between Corbin Russwin and New Britain station and on to East Street making all local stops.",
    "One Way Mileage": "7.6 miles",
    "One Way Travel Time": "30 minutes",
    "Service Span": "Seven days a week, 18 hours a day on Monday to Saturday (6am to Midnight) and 12 hours (8 am to 8pm) on Sundays.",
    "Weekday AM Peak": "60",
    "Weekday Midday": "60",
    "Weekday PM Peak": "60",
    "Weekday Evening": "60",
    "Saturday AM Peak": "",
    "Saturday Midday": "60",
    "Saturday PM Peak": "",
    "Saturday Evening": "60",
    "Sunday AM Peak": "",
    "Sunday Midday": "60",
    "Sunday PM Peak": "",
    "Sunday Evening": ""
  },

  "BW1 New Britain to Hartford Shuttle": {
    "One Way Travel Time": "28 minutes",
    "One Way Mileage": "10.1 miles",
    "Service Pattern": "This route will make all local station stops along its route including: New Britain, East Main, East Street, Cedar Street, Newington Jct., Elmwood, Flatbush Avenue, Kane Street, Park Street, Sigourney Street, Union Station and in downtown Hartford, Ann Street, Trumbull Street and Main Street. The route will travel exclusively on the busway except for the downtown loop from Union Station to Main Street.",
    "Service Span": "Seven days a week, 18 hours a day on Monday to Saturday (6am to Midnitght) and 12 hours (8am to 8pm) on Sundays.",
    "Weekday AM Peak": "12",
    "Weekday Midday": "20",
    "Weekday PM Peak": "12",
    "Weekday Evening": "30",
    "Saturday AM Peak": "",
    "Saturday Midday": "20",
    "Saturday PM Peak": "",
    "Saturday Evening": "30",
    "Sunday AM Peak": "",
    "Sunday Midday": "30",
    "Sunday PM Peak": "",
    "Sunday Evening": ""

  },

  "BW2 Bristol to Hartford Shuttle": {
    "One Way Travel Time": "50 minutes",
    "One Way Mileage": "20.1 miles",
    "Service Pattern": "From Bristol this route will make limited stops along Rt. 72 to New Britain and the busway. Once on the busway, this route will make all local station stops along its route including: New Britain, East Main, East Street, Cedar Street, Newington Jct., Elmwood, Flatbush Avenue, Kane Street, Park Street, Sigourney Street, Union Station and in downtown Hartford, Ann Street, Trumbull Street and Main Street. The route will travel exclusively on the busway except for the downtown loop from Union Station to Main Street.",
    "Service Span": "Seven days a week, 18 hours a day on Monday to Saturday (6am to Midnitght) and 12 hours (8am to 8pm) on Sundays.",
    "Weekday AM Peak": "12",
    "Weekday Midday": "20",
    "Weekday PM Peak": "12",
    "Weekday Evening": "30",
    "Saturday AM Peak": "",
    "Saturday Midday": "20",
    "Saturday PM Peak": "",
    "Saturday Evening": "30",
    "Sunday AM Peak": "",
    "Sunday Midday": "30",
    "Sunday PM Peak": "",
    "Sunday Evening": ""

  },
  "BW3 New Britain-Westfarms-Hartford": {
    "One Way Travel Time": "44 minutes",
    "One Way Mileage": "11.5 miles",
    "Service Pattern": "This route will stop at all local bus stops along its route from downtown New Britain to Westfarms and then through Elmwood to the busway. After it enters the busway at Oakwood, it will make all local busway stops at Flatbush, Kane Street, Park Street, Sigourney Street, and Union Station. On-street in downtown Hartford it will stop at Anne, Trumbull, and Main Streets.",
    "Service Span": "Seven days a week, 18 hours a day on Monday to Saturday (6am to Midnitght) and 16 hours (8am to Midnight) on Sundays.",
    "Weekday AM Peak": "18",
    "Weekday Midday": "20",
    "Weekday PM Peak": "18",
    "Weekday Evening": "60",
    "Saturday AM Peak": "",
    "Saturday Midday": "20",
    "Saturday PM Peak": "",
    "Saturday Evening": "60",
    "Sunday AM Peak": "",
    "Sunday Midday": "60",
    "Sunday PM Peak": "",
    "Sunday Evening": ""
  },
  "BW4 UConn Health-Westfarms-Hartford": {
    "One Way Travel Time": "43 minutes",
    "One Way Mileage": "9.1 miles",
    "Service Pattern": "This route will stop at all local bus stops along its route from UConn Health Center to Westfarms and then through Elmwood to the busway. After it enters the busway at Oakwood, it will make all local busway stops at Flatbush, Kane Street, Park Street, Sigourney Street, and Union Station. On-street in downtown Hartford it will stop at Anne, Trumbull, and Main Streets.",
    "Service Span": "Seven days a week, 18 hours a day on Monday to Saturday (6am to Midnitght) and 12 hours (8am to 8pm) on Sundays.",
    "Weekday AM Peak": "18",
    "Weekday Midday": "20",
    "Weekday PM Peak": "18",
    "Weekday Evening": "60",
    "Saturday AM Peak": "",
    "Saturday Midday": "20",
    "Saturday PM Peak": "",
    "Saturday Evening": "60",
    "Sunday AM Peak": "",
    "Sunday Midday": "60",
    "Sunday PM Peak": "",
    "Sunday Evening": ""
  },
  "BW5 Newington Junction to Hartford Shuttle": {
    "One Way Travel Time": "16 minutes",
    "One Way Mileage": "6.0 miles",
    "Service Pattern": "This route makes all local stops along the busway starting in Newington Junction and including Elmwood, Flatbush, Kane Street, Park Street, Sigourney Street, and Union Station. In downtown Hartford it stops on-street at Ann, Trumbull, and Main.",
    "Service Span": "This route will operate only on weekdays during AM and PM peak periods, from 6am to 9am and from 3pm to 6pm.",
    "Weekday AM Peak": "18",
    "Weekday Midday": "",
    "Weekday PM Peak": "18",
    "Weekday Evening": "",
    "Saturday AM Peak": "",
    "Saturday Midday": "",
    "Saturday PM Peak": "",
    "Saturday Evening": "",
    "Sunday AM Peak": "",
    "Sunday Midday": "",
    "Sunday PM Peak": "",
    "Sunday Evening": ""
  }
}
